### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by bissim**
Here is a preliminary translation for “Mark post unread”.
While it's in singular number, I translated its name as if it were “Mark posts unread”.

### CODE REVIEW

**Comment by kasimi** [comment]
Thanks for your work. The language file was updated for 1.0.1, would you mind adjusting it?

**Comment by bissim** [comment]
I'll sort things out in a while.

**Comment by bissim** [comment]
@kasimi done.

**Comment by kasimi** [comment]
Thanks! :+1:

**Pull request merged**
